name: Test Pre-Release

on:
  release:
    types:
    - prereleased

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo "THIS IS A PRE-RELEASE"
    - name: Tag
      run: echo ${{ github.ref_name }}